language: dart
with_content_shell: true
script: pub run test -p content-shell -p firefox
sudo: false
dart:
  - stable
  - dev
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
