name: notification
description: >
  Implement the Notification element using JS interop
version: 0.0.1
author: Dart Team <misc@dartlang.org>
dependencies:
  browser: '>=0.10.0 <0.12.0'
dev_dependencies:
  unittest: any
